# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GTTabBar' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  # Pods for GTTabBar
  
  #pod 'LookinServer', '0.9.4', :configurations => ['Debug']
  pod 'Masonry'
  pod 'SDWebImage','4.3.3'
  pod 'SDWebImage/GIF'
  pod 'FLAnimatedImage'
  
  target 'GTTabBarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GTTabBarUITests' do
    # Pods for testing
  end

end
